// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cog-forge/rolecue/api/internal/config"
	"github.com/cog-forge/rolecue/api/internal/pkg/logger"
	"github.com/cog-forge/rolecue/api/internal/pkg/tracer"
	"github.com/cog-forge/rolecue/api/internal/provider"
	"github.com/cog-forge/rolecue/api/internal/server"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func InitializeApplication(configPath string) (*Application, func(), error) {
	config, err := provider.ProvideConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup, err := provider.ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup2, err := provider.ProvideDatabasePool(config, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := provider.ProvideAuthRepository(pool)
	authService := provider.ProvideAuthService(config, repository)
	authHandler := provider.ProvideAuthHandler(authService)
	healthHandler := provider.ProvideHealthHandler()
	repositoryRepository := provider.ProvideJDRepository(pool)
	application, err := provider.ProvideJDService(config, repositoryRepository)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	jdHandler := provider.ProvideJDHandler(application)
	engine := provider.ProvideRouter(config, logger, authHandler, healthHandler, jdHandler)
	server := provider.ProvideHTTPServer(config, engine, logger)
	tracer, cleanup3, err := provider.ProvideTracer(config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainApplication := &Application{
		Server: server,
		Pool:   pool,
		Logger: logger,
		Tracer: tracer,
		Config: config,
	}
	return mainApplication, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Application struct {
	Server *server.Server
	Pool   *pgxpool.Pool
	Logger *logger.Logger
	Tracer *tracer.Tracer
	Config *config.Config
}
