// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getAuthUser = `-- name: GetAuthUser :one
SELECT id, email, name, coalesce(role, 'candidate')::text AS role,
       email_verified, coalesce(is_locked, false)::boolean AS is_locked, image
FROM public.users
WHERE id = $1
`

type GetAuthUserRow struct {
	ID            uuid.UUID
	Email         string
	Name          string
	Role          string
	EmailVerified bool
	IsLocked      bool
	Image         *string
}

func (q *Queries) GetAuthUser(ctx context.Context, id uuid.UUID) (GetAuthUserRow, error) {
	row := q.db.QueryRow(ctx, getAuthUser, id)
	var i GetAuthUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.EmailVerified,
		&i.IsLocked,
		&i.Image,
	)
	return i, err
}
