BEGIN;
-- Cutover on the isolated dev DB. Preserve owner UUIDs and business rows,
-- but deliberately invalidate legacy credentials and all legacy sessions.
ALTER TABLE public.accounts RENAME TO legacy_auth_accounts;
-- Generated by Better Auth 1.7.7; do not apply separately from Go migrations.
create table "users" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "name" text not null, "email" text not null unique, "email_verified" boolean not null, "image" text, "created_at" timestamptz default CURRENT_TIMESTAMP not null, "updated_at" timestamptz default CURRENT_TIMESTAMP not null, "role" text, "is_locked" boolean, "lock_reason" text, "lock_expires_at" timestamptz, "two_factor_enabled" boolean);

create table "sessions" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "expires_at" timestamptz not null, "token" text not null unique, "created_at" timestamptz default CURRENT_TIMESTAMP not null, "updated_at" timestamptz not null, "ip_address" text, "user_agent" text, "user_id" uuid not null references "users" ("id") on delete cascade, "impersonated_by" text);

create table "accounts" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "account_id" text not null, "provider_id" text not null, "user_id" uuid not null references "users" ("id") on delete cascade, "access_token" text, "refresh_token" text, "id_token" text, "access_token_expires_at" timestamptz, "refresh_token_expires_at" timestamptz, "scope" text, "password" text, "created_at" timestamptz default CURRENT_TIMESTAMP not null, "updated_at" timestamptz not null);

create table "verifications" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "identifier" text not null, "value" text not null, "expires_at" timestamptz not null, "created_at" timestamptz default CURRENT_TIMESTAMP not null, "updated_at" timestamptz default CURRENT_TIMESTAMP not null);

create table "two_factors" ("id" uuid default pg_catalog.gen_random_uuid() not null primary key, "secret" text not null, "backup_codes" text not null, "user_id" uuid not null references "users" ("id") on delete cascade, "verified" boolean, "failed_verification_count" integer, "locked_until" timestamptz);

create index "sessions_user_id_idx" on "sessions" ("user_id");

create index "accounts_user_id_idx" on "accounts" ("user_id");

create index "verifications_identifier_idx" on "verifications" ("identifier");

create index "two_factors_secret_idx" on "two_factors" ("secret");

create index "two_factors_user_id_idx" on "two_factors" ("user_id");

ALTER TABLE public.users ALTER COLUMN role SET DEFAULT 'candidate';
ALTER TABLE public.users ADD CONSTRAINT users_role_check CHECK (role IN ('candidate', 'recruiter', 'admin'));
ALTER TABLE public.users ALTER COLUMN is_locked SET DEFAULT false;
ALTER TABLE public.users ALTER COLUMN two_factor_enabled SET DEFAULT false;
INSERT INTO public.users (id, name, email, email_verified, role, is_locked, created_at, updated_at)
SELECT id, full_name, email, false,
 CASE role::text WHEN 'admin' THEN 'admin' WHEN 'jury' THEN 'recruiter' ELSE 'candidate' END,
 is_locked, created_at, updated_at FROM public.legacy_auth_accounts;
ALTER TABLE public.job_descriptions DROP CONSTRAINT job_descriptions_user_id_fkey;
ALTER TABLE public.job_descriptions ADD CONSTRAINT job_descriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.interview_sessions DROP CONSTRAINT interview_sessions_user_id_fkey;
ALTER TABLE public.interview_sessions ADD CONSTRAINT interview_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
DROP TABLE public.legacy_auth_accounts;
COMMIT;
