// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countTransactionsByUserID = `-- name: CountTransactionsByUserID :one
SELECT COUNT(*)
FROM public.transactions
WHERE "from" = $1 OR "to" = $1
`

func (q *Queries) CountTransactionsByUserID(ctx context.Context, txUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactionsByUserID, txUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO public.wallets (user_id, balance)
VALUES ($1, 0)
RETURNING id, user_id, balance
`

func (q *Queries) CreateWallet(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet, userID)
	var i Wallet
	err := row.Scan(&i.ID, &i.UserID, &i.Balance)
	return i, err
}

const getCoinPackageByID = `-- name: GetCoinPackageByID :one
SELECT id, name, price, description, amount, currency
FROM public.coin_packages
WHERE id = $1
`

func (q *Queries) GetCoinPackageByID(ctx context.Context, id uuid.UUID) (CoinPackage, error) {
	row := q.db.QueryRow(ctx, getCoinPackageByID, id)
	var i CoinPackage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Description,
		&i.Amount,
		&i.Currency,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, "from", "to", amount, currency, description, status, payos_order_code
FROM public.transactions
WHERE id = $1
`

type GetTransactionByIDRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.PayosOrderCode,
	)
	return i, err
}

const getTransactionByPayOSOrderCode = `-- name: GetTransactionByPayOSOrderCode :one
SELECT id, "from", "to", amount, currency, description, status, payos_order_code
FROM public.transactions
WHERE payos_order_code = $1
`

type GetTransactionByPayOSOrderCodeRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) GetTransactionByPayOSOrderCode(ctx context.Context, payosOrderCode *string) (GetTransactionByPayOSOrderCodeRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByPayOSOrderCode, payosOrderCode)
	var i GetTransactionByPayOSOrderCodeRow
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.PayosOrderCode,
	)
	return i, err
}

const getTransactionByPayOSOrderCodeForUpdate = `-- name: GetTransactionByPayOSOrderCodeForUpdate :one
SELECT id, "from", "to", amount, currency, description, status, payos_order_code
FROM public.transactions
WHERE payos_order_code = $1
FOR UPDATE
`

type GetTransactionByPayOSOrderCodeForUpdateRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) GetTransactionByPayOSOrderCodeForUpdate(ctx context.Context, payosOrderCode *string) (GetTransactionByPayOSOrderCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByPayOSOrderCodeForUpdate, payosOrderCode)
	var i GetTransactionByPayOSOrderCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.PayosOrderCode,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, balance
FROM public.wallets
WHERE user_id = $1
`

func (q *Queries) GetWalletByUserID(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserID, userID)
	var i Wallet
	err := row.Scan(&i.ID, &i.UserID, &i.Balance)
	return i, err
}

const getWalletByUserIDForUpdate = `-- name: GetWalletByUserIDForUpdate :one
SELECT id, user_id, balance
FROM public.wallets
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetWalletByUserIDForUpdate(ctx context.Context, userID uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserIDForUpdate, userID)
	var i Wallet
	err := row.Scan(&i.ID, &i.UserID, &i.Balance)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO public.transactions ("from", "to", amount, currency, description, status, payos_order_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, "from", "to", amount, currency, description, status, payos_order_code
`

type InsertTransactionParams struct {
	TxFrom         string
	TxTo           string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

type InsertTransactionRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.TxFrom,
		arg.TxTo,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.Status,
		arg.PayosOrderCode,
	)
	var i InsertTransactionRow
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.PayosOrderCode,
	)
	return i, err
}

const listActiveCoinPackages = `-- name: ListActiveCoinPackages :many
SELECT id, name, price, description, amount, currency
FROM public.coin_packages
ORDER BY price ASC
`

func (q *Queries) ListActiveCoinPackages(ctx context.Context) ([]CoinPackage, error) {
	rows, err := q.db.Query(ctx, listActiveCoinPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoinPackage
	for rows.Next() {
		var i CoinPackage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Description,
			&i.Amount,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserID = `-- name: ListTransactionsByUserID :many
SELECT id, "from", "to", amount, currency, description, status, payos_order_code
FROM public.transactions
WHERE "from" = $1 OR "to" = $1
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type ListTransactionsByUserIDParams struct {
	TxUserID   string
	PageOffset int32
	PageLimit  int32
}

type ListTransactionsByUserIDRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]ListTransactionsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserID, arg.TxUserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByUserIDRow
	for rows.Next() {
		var i ListTransactionsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.From,
			&i.To,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.Status,
			&i.PayosOrderCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE public.transactions
SET status = $1
WHERE id = $2
RETURNING id, "from", "to", amount, currency, description, status, payos_order_code
`

type UpdateTransactionStatusParams struct {
	Status TransactionStatus
	ID     uuid.UUID
}

type UpdateTransactionStatusRow struct {
	ID             uuid.UUID
	From           string
	To             string
	Amount         int32
	Currency       string
	Description    *string
	Status         TransactionStatus
	PayosOrderCode *string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (UpdateTransactionStatusRow, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus, arg.Status, arg.ID)
	var i UpdateTransactionStatusRow
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.To,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.Status,
		&i.PayosOrderCode,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE public.wallets
SET balance = $1
WHERE id = $2
RETURNING id, user_id, balance
`

type UpdateWalletBalanceParams struct {
	Balance int32
	ID      uuid.UUID
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.Balance, arg.ID)
	var i Wallet
	err := row.Scan(&i.ID, &i.UserID, &i.Balance)
	return i, err
}
