const segment = (value: string) => encodeURIComponent(value);
export const routes = {
  home: "/",
  pricing: "/pricing",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  targetJds: "/target-jds",
  avatarStudio: "/avatar-studio",
  jobs: "/jobs",
  applications: "/applications",
  afterEmailVerification: "/dashboard?auth=email-verified",
  terms: "/terms",
  privacy: "/privacy",
  history: "/history",
  billing: "/billing",
  profile: "/profile",
  settings: "/settings",
  interviews: {
    root: "/interviews",
    new: {
      jobDescription: "/interviews/new/job-description",
      skills: "/interviews/new/skills",
      setup: "/interviews/new/setup",
      interviewer: "/interviews/new/interviewer",
      preflight: "/interviews/new/preflight",
    },
    room: (id: string) => `/interviews/${segment(id)}/room`,
  },
  reports: { detail: (id: string) => `/reports/${segment(id)}` },
  recruiter: {
    root: "/recruiter",
    dashboard: "/recruiter/dashboard",
    jobPostings: "/recruiter/job-postings",
    applications: "/recruiter/applications",
  },
  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    interviews: "/admin/interviews",
    domains: "/admin/domains",
    questions: "/admin/questions",
    avatars: "/admin/avatars",
    voices: "/admin/voices",
    billing: "/admin/billing",
    settings: "/admin/settings",
    jobPostings: "/admin/job-postings",
    aiBehaviour: "/admin/ai-behaviour",
    evaluationCriteria: "/admin/evaluation-criteria",
    revenue: "/admin/revenue",
  },
} as const;
