// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questionbank.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addCoreQuestion = `-- name: AddCoreQuestion :one
INSERT INTO public.core_questions (jd_id, content)
SELECT jp.jd_id, $1::text
FROM public.job_postings jp
WHERE jp.id = $2 AND jp.recruiter_id = $3 AND jp.status = 'pending'
RETURNING id, content
`

type AddCoreQuestionParams struct {
	Content     string
	PostingID   uuid.UUID
	RecruiterID uuid.UUID
}

type AddCoreQuestionRow struct {
	ID      uuid.UUID
	Content string
}

func (q *Queries) AddCoreQuestion(ctx context.Context, arg AddCoreQuestionParams) (AddCoreQuestionRow, error) {
	row := q.db.QueryRow(ctx, addCoreQuestion, arg.Content, arg.PostingID, arg.RecruiterID)
	var i AddCoreQuestionRow
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}

const candidateOwnsJD = `-- name: CandidateOwnsJD :one
SELECT EXISTS(
    SELECT 1 FROM public.role_profiles
    WHERE jd_id = $1 AND candidate_id = $2
)
`

type CandidateOwnsJDParams struct {
	JdID        uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) CandidateOwnsJD(ctx context.Context, arg CandidateOwnsJDParams) (bool, error) {
	row := q.db.QueryRow(ctx, candidateOwnsJD, arg.JdID, arg.CandidateID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countCoreQuestions = `-- name: CountCoreQuestions :one
SELECT count(*) FROM public.core_questions WHERE jd_id = $1
`

func (q *Queries) CountCoreQuestions(ctx context.Context, jdID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCoreQuestions, jdID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCoreQuestion = `-- name: DeleteCoreQuestion :execrows
DELETE FROM public.core_questions cq
USING public.job_postings jp
WHERE cq.id = $1
  AND cq.jd_id = jp.jd_id
  AND jp.id = $2
  AND jp.recruiter_id = $3
  AND jp.status = 'pending'
`

type DeleteCoreQuestionParams struct {
	ID          uuid.UUID
	PostingID   uuid.UUID
	RecruiterID uuid.UUID
}

func (q *Queries) DeleteCoreQuestion(ctx context.Context, arg DeleteCoreQuestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCoreQuestion, arg.ID, arg.PostingID, arg.RecruiterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJDRefinementNote = `-- name: GetJDRefinementNote :one
SELECT refinement_note FROM public.job_descriptions WHERE id = $1
`

func (q *Queries) GetJDRefinementNote(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getJDRefinementNote, id)
	var refinement_note *string
	err := row.Scan(&refinement_note)
	return refinement_note, err
}

const getRecruiterPosting = `-- name: GetRecruiterPosting :one
SELECT jd_id, status::text AS status
FROM public.job_postings
WHERE id = $1 AND recruiter_id = $2
`

type GetRecruiterPostingParams struct {
	ID          uuid.UUID
	RecruiterID uuid.UUID
}

type GetRecruiterPostingRow struct {
	JdID   uuid.UUID
	Status string
}

func (q *Queries) GetRecruiterPosting(ctx context.Context, arg GetRecruiterPostingParams) (GetRecruiterPostingRow, error) {
	row := q.db.QueryRow(ctx, getRecruiterPosting, arg.ID, arg.RecruiterID)
	var i GetRecruiterPostingRow
	err := row.Scan(&i.JdID, &i.Status)
	return i, err
}

const insertCoreQuestions = `-- name: InsertCoreQuestions :many
INSERT INTO public.core_questions (jd_id, content)
SELECT $1::uuid, unnest($2::text[])
RETURNING id, content
`

type InsertCoreQuestionsParams struct {
	JdID     uuid.UUID
	Contents []string
}

type InsertCoreQuestionsRow struct {
	ID      uuid.UUID
	Content string
}

func (q *Queries) InsertCoreQuestions(ctx context.Context, arg InsertCoreQuestionsParams) ([]InsertCoreQuestionsRow, error) {
	rows, err := q.db.Query(ctx, insertCoreQuestions, arg.JdID, arg.Contents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertCoreQuestionsRow
	for rows.Next() {
		var i InsertCoreQuestionsRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoreQuestions = `-- name: ListCoreQuestions :many
SELECT id, content
FROM public.core_questions
WHERE jd_id = $1
ORDER BY id
`

type ListCoreQuestionsRow struct {
	ID      uuid.UUID
	Content string
}

// Ids are random UUIDs, so this order is stable between reads but unrelated to generation order;
// core_questions has no position column and the frozen schema must not change.
func (q *Queries) ListCoreQuestions(ctx context.Context, jdID uuid.UUID) ([]ListCoreQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listCoreQuestions, jdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoreQuestionsRow
	for rows.Next() {
		var i ListCoreQuestionsRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequirementsForJD = `-- name: ListRequirementsForJD :many
SELECT name, target, type::text AS type, evidence_text
FROM public.requirements
WHERE jd_id = $1
ORDER BY name, id
`

type ListRequirementsForJDRow struct {
	Name         string
	Target       string
	Type         string
	EvidenceText *string
}

func (q *Queries) ListRequirementsForJD(ctx context.Context, jdID uuid.UUID) ([]ListRequirementsForJDRow, error) {
	rows, err := q.db.Query(ctx, listRequirementsForJD, jdID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequirementsForJDRow
	for rows.Next() {
		var i ListRequirementsForJDRow
		if err := rows.Scan(
			&i.Name,
			&i.Target,
			&i.Type,
			&i.EvidenceText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCandidateRoleProfile = `-- name: LockCandidateRoleProfile :one
SELECT jd_id
FROM public.role_profiles
WHERE jd_id = $1 AND candidate_id = $2
FOR UPDATE
`

type LockCandidateRoleProfileParams struct {
	JdID        uuid.UUID
	CandidateID uuid.UUID
}

func (q *Queries) LockCandidateRoleProfile(ctx context.Context, arg LockCandidateRoleProfileParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCandidateRoleProfile, arg.JdID, arg.CandidateID)
	var jd_id uuid.UUID
	err := row.Scan(&jd_id)
	return jd_id, err
}

const lockPendingPosting = `-- name: LockPendingPosting :one
SELECT jd_id
FROM public.job_postings
WHERE id = $1 AND recruiter_id = $2 AND status = 'pending'
FOR UPDATE
`

type LockPendingPostingParams struct {
	ID          uuid.UUID
	RecruiterID uuid.UUID
}

func (q *Queries) LockPendingPosting(ctx context.Context, arg LockPendingPostingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPendingPosting, arg.ID, arg.RecruiterID)
	var jd_id uuid.UUID
	err := row.Scan(&jd_id)
	return jd_id, err
}

const updateCoreQuestion = `-- name: UpdateCoreQuestion :one
UPDATE public.core_questions cq
SET content = $1::text
FROM public.job_postings jp
WHERE cq.id = $2
  AND cq.jd_id = jp.jd_id
  AND jp.id = $3
  AND jp.recruiter_id = $4
  AND jp.status = 'pending'
RETURNING cq.id, cq.content
`

type UpdateCoreQuestionParams struct {
	Content     string
	ID          uuid.UUID
	PostingID   uuid.UUID
	RecruiterID uuid.UUID
}

type UpdateCoreQuestionRow struct {
	ID      uuid.UUID
	Content string
}

func (q *Queries) UpdateCoreQuestion(ctx context.Context, arg UpdateCoreQuestionParams) (UpdateCoreQuestionRow, error) {
	row := q.db.QueryRow(ctx, updateCoreQuestion,
		arg.Content,
		arg.ID,
		arg.PostingID,
		arg.RecruiterID,
	)
	var i UpdateCoreQuestionRow
	err := row.Scan(&i.ID, &i.Content)
	return i, err
}
