// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, email, image, coalesce(role, 'candidate')::text AS role,
       email_verified, company_name, company_website, created_at, updated_at
FROM public.users
WHERE id = $1
`

type GetProfileRow struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Image          *string
	Role           string
	EmailVerified  bool
	CompanyName    *string
	CompanyWebsite *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProfile(ctx context.Context, id uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i GetProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Image,
		&i.Role,
		&i.EmailVerified,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const profileExists = `-- name: ProfileExists :one
SELECT EXISTS(SELECT 1 FROM public.users WHERE id = $1)
`

func (q *Queries) ProfileExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, profileExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE public.users SET
    name = CASE WHEN $1::boolean THEN $2::text ELSE name END,
    image = CASE WHEN $3::boolean THEN $4::text ELSE image END,
    company_name = CASE WHEN $5::boolean THEN $6::text ELSE company_name END,
    company_website = CASE WHEN $7::boolean THEN $8::text ELSE company_website END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9
    AND coalesce(role, 'candidate') = $10::text
    AND NOT coalesce(is_locked, false) AND email_verified
RETURNING id, name, email, image, coalesce(role, 'candidate')::text AS role,
          email_verified, company_name, company_website, created_at, updated_at
`

type UpdateProfileParams struct {
	SetName           bool
	Name              *string
	SetImage          bool
	Image             *string
	SetCompanyName    bool
	CompanyName       *string
	SetCompanyWebsite bool
	CompanyWebsite    *string
	ID                uuid.UUID
	Role              string
}

type UpdateProfileRow struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Image          *string
	Role           string
	EmailVerified  bool
	CompanyName    *string
	CompanyWebsite *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.SetName,
		arg.Name,
		arg.SetImage,
		arg.Image,
		arg.SetCompanyName,
		arg.CompanyName,
		arg.SetCompanyWebsite,
		arg.CompanyWebsite,
		arg.ID,
		arg.Role,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Image,
		&i.Role,
		&i.EmailVerified,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
